vim.keymap.set('n', '<leader>m', require('harpoon.mark').add_file, { desc = '[M]ark file' })
vim.keymap.set('n', '<leader>l', require('harpoon.ui').toggle_quick_menu, { desc = '[L]ist marks' })
vim.keymap.set('n', '<leader>1', function() require('harpoon.ui').nav_file(1) end, { desc = 'Go to file 1' })
vim.keymap.set('n', '<leader>2', function() require('harpoon.ui').nav_file(2) end, { desc = 'Go to file 2' })
vim.keymap.set('n', '<leader>3', function() require('harpoon.ui').nav_file(3) end, { desc = 'Go to file 3' })
vim.keymap.set('n', '<leader>4', function() require('harpoon.ui').nav_file(4) end, { desc = 'Go to file 4' })
vim.keymap.set('n', '<leader>5', function() require('harpoon.ui').nav_file(5) end, { desc = 'Go to file 5' })
vim.keymap.set('n', '<leader>6', function() require('harpoon.ui').nav_file(6) end, { desc = 'Go to file 6' })
